# This file was generated by GoReleaser. DO NOT EDIT.
cask "raypaste" do
  name "raypaste"
  desc "Ultra-fast AI-optimized meta prompts from your input text in your terminal"
  homepage "https://github.com/raypaste/raypaste-cli"
  version "0.2.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "raypaste"

  on_macos do
    on_intel do
      url "https://github.com/raypaste/raypaste-cli/releases/download/v#{version}/raypaste-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/raypaste/raypaste-cli/releases/download"
      sha256 "287b1f2ab960f9da1b582b1961d1e13c3310ae658a82f7b49647ed0920a22f70"
    end
    on_arm do
      url "https://github.com/raypaste/raypaste-cli/releases/download/v#{version}/raypaste-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/raypaste/raypaste-cli/releases/download"
      sha256 "7686ff5adf87ce6a2975e0a8192ccb574deddd2d901f83dd7ed7838f62a5ffbf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/raypaste/raypaste-cli/releases/download/v#{version}/raypaste-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/raypaste/raypaste-cli/releases/download"
      sha256 "b65b0994aa2b35d803c9398242eb2df453983fb1f731b6de7370194f2e061d28"
    end
    on_arm do
      url "https://github.com/raypaste/raypaste-cli/releases/download/v#{version}/raypaste-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/raypaste/raypaste-cli/releases/download"
      sha256 "7ba423ff81886b59a74f8365b3e8d7c738be39b191a3cf4569230f27bb8119de"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/raypaste"]
    end
  end

  # No zap stanza required
end
