# This file was generated by GoReleaser. DO NOT EDIT.
cask "raypaste" do
  name "raypaste"
  desc "Ultra-fast AI-optimized meta prompts from your input text in your terminal"
  homepage "https://github.com/raypaste/raypaste-cli"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "raypaste"

  on_macos do
    on_intel do
      url "https://github.com/raypaste/raypaste-cli/releases/download/v#{version}/raypaste-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/raypaste/raypaste-cli/releases/download"
      sha256 "95724164efa65e5f3d38c3a8a31e3670d55f28136ed61b93a37cdacbd6bf0b74"
    end
    on_arm do
      url "https://github.com/raypaste/raypaste-cli/releases/download/v#{version}/raypaste-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/raypaste/raypaste-cli/releases/download"
      sha256 "748e2b20336ea2eec5ca5a9076a96ded53b83541edd9b5905a8ddab6191c19d1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/raypaste/raypaste-cli/releases/download/v#{version}/raypaste-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/raypaste/raypaste-cli/releases/download"
      sha256 "dea0b4c3c82f5315c79b01bc61cef896f5e2840646b0cebb6570238af7b8de0d"
    end
    on_arm do
      url "https://github.com/raypaste/raypaste-cli/releases/download/v#{version}/raypaste-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/raypaste/raypaste-cli/releases/download"
      sha256 "2e9d46a61521f0fd76584a68e86f1d4b172680b99188de57be9b452dc57a5466"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/raypaste"]
    end
  end

  # No zap stanza required
end
