# This file was generated by GoReleaser. DO NOT EDIT.
cask "raypaste" do
  name "raypaste"
  desc "Ultra-fast AI-optimized meta prompts from your input text in your terminal"
  homepage "https://github.com/raypaste/raypaste-cli"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "raypaste"

  on_macos do
    on_intel do
      url "https://github.com/raypaste/raypaste-cli/releases/download/v#{version}/raypaste-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/raypaste/raypaste-cli/releases/download"
      sha256 "28d4018761a79c20740227f03327ae1a6852c60d40999f8781f069cfe0e685ce"
    end
    on_arm do
      url "https://github.com/raypaste/raypaste-cli/releases/download/v#{version}/raypaste-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/raypaste/raypaste-cli/releases/download"
      sha256 "d2f666e258312df34b82b1ba08dc806fdbe0d9d545f9ca2375eff01b47f12bf5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/raypaste/raypaste-cli/releases/download/v#{version}/raypaste-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/raypaste/raypaste-cli/releases/download"
      sha256 "f1efa79ad249dfe90a0980ebeb957751eb26116ab9bb0f23b894c6fa22637271"
    end
    on_arm do
      url "https://github.com/raypaste/raypaste-cli/releases/download/v#{version}/raypaste-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/raypaste/raypaste-cli/releases/download"
      sha256 "54069f3d8fad6b1b0257b6f4ab44c0ede0b6dbfd9062bf85bce105caeb703441"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/raypaste"]
    end
  end

  # No zap stanza required
end
